### ISSUE TITLE
cookie fail

### ISSUE THREAD

**Issue by wclifton1** [bittner/lego-mindstorms-ev3-comparison#14]
happening in firefox and chrome... am i doing something wrong?
```python
* Accept Lego's website cookies
Traceback (most recent call last):
  File "lego.py", line 183, in <module>
    main()
  File "lego.py", line 91, in main
    function(**kwargs)
  File "lego.py", line 179, in order
    order.process(lego_set, order_list)
  File "/Users/wclifton1/Documents/GitHub/lego-mindstorms-ev3-comparison/legoshop.py", line 540, in process
    self._process_cookies_accept()
  File "/Users/wclifton1/Documents/GitHub/lego-mindstorms-ev3-comparison/legoshop.py", line 282, in _process_cookies_accept
    cookie_button[0].click()
IndexError: list index out of range
```

**Comment by bittner** [comment]
It looks like there is [no button anymore](https://github.com/bittner/lego-mindstorms-ev3-comparison/blob/master/legoshop.py#L280-L282), or none with a `class="l-accept__btn"` attribute on the page being evaluated. Or the page did load too slowly.
